"use client";

import { ChangeEvent, DragEvent, FormEvent, useEffect, useMemo, useRef, useState } from "react";

type Category = "Food & Dining" | "Shopping" | "Transport" | "Bills & Utilities" | "Rent" | "Entertainment" | "Health" | "Income" | "Other";
type Transaction = { id: string; date: string; description: string; amount: number; category: Category; confidence: number; local: boolean; corrected?: boolean };
type SignedInUser = { id?: string; displayName: string; email: string; emailVerified?: boolean } | null;
type Analysis = { id: string; fileName: string; summary: string; transactions: Transaction[]; model?: string | null; metrics?: {accuracy?:number|null;trained?:boolean}|null; createdAt: string };
const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:3001";

const palette: Record<Category, string> = {
  "Food & Dining": "#ff8a65", Shopping: "#8758ff", Transport: "#45b6fe", "Bills & Utilities": "#f5c451",
  Rent: "#f06b9c", Entertainment: "#51c7a5", Health: "#ef6a6a", Income: "#78b159", Other: "#9aa0a6",
};

function money(value: number) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value); }

export default function Dashboard({ initialUser }: { initialUser: SignedInUser }) {
  const [transactions, setTransactions] = useState<Transaction[]>([]); const [fileName, setFileName] = useState("No statement uploaded");
  const [dragging, setDragging] = useState(false); const [query, setQuery] = useState(""); const [tab, setTab] = useState<"home" | "overview" | "transactions" | "fairness" | "account">("home");
  const [showUpload, setShowUpload] = useState(false); const input = useRef<HTMLInputElement>(null);
  const [showDemo, setShowDemo] = useState(false); const [demoStep, setDemoStep] = useState(0); const [demoPlaying, setDemoPlaying] = useState(true);
  const [user, setUser] = useState<SignedInUser>(initialUser); const [authMode, setAuthMode] = useState<"login" | "signup" | "forgot" | "reset" | null>(null); const [resetToken,setResetToken]=useState("");
  const [authError, setAuthError] = useState(""); const [authBusy, setAuthBusy] = useState(false);
  const [analysisId, setAnalysisId] = useState<string|null>(null); const [summaryText,setSummaryText]=useState(""); const [analyses,setAnalyses]=useState<Analysis[]>([]); const [uploadBusy,setUploadBusy]=useState(false); const [uploadError,setUploadError]=useState("");
  const [theme, setTheme] = useState<"light" | "dark">("light");
  const isAuthenticated = Boolean(user);
  const toggleTheme = () => setTheme(current => current === "light" ? "dark" : "light");
  const demoScenes = [
    { number: "01", title: "Upload a statement", body: "Choose a bank CSV, XLSX or text-based PDF. Spend Sense reads the date, merchant and amount without changing the original file.", visual: "upload" },
    { number: "02", title: "See the overview", body: "Get total spending, income, transaction count and a category breakdown in one view.", visual: "overview" },
    { number: "03", title: "Review categories", body: "Search every payment and correct a category directly when the prediction is wrong.", visual: "transactions" },
    { number: "04", title: "Check fairness", body: "Compare confidence for known brands and local merchants to reveal where the model needs work.", visual: "fairness" },
    { number: "05", title: "Make better decisions", body: "Turn a messy statement into a clear monthly picture—without reading hundreds of bank rows.", visual: "result" },
  ];
  useEffect(() => { if (!showDemo || !demoPlaying) return; const timer = window.setInterval(() => setDemoStep(step => (step + 1) % demoScenes.length), 4200); return () => window.clearInterval(timer); }, [showDemo, demoPlaying, demoScenes.length]);
  useEffect(() => { const controller = new AbortController(); fetch(`${API_URL}/api/auth/me`, { credentials: "include", signal: controller.signal }).then(response => response.ok ? response.json() : { user: null }).then(body => { if (body.user) setUser({ id: body.user.id, displayName: body.user.name, email: body.user.email, emailVerified:body.user.emailVerified }); }).catch(()=>{}); return () => controller.abort(); }, []);
  useEffect(()=>{if(!user)return;fetch(`${API_URL}/api/analyses`,{credentials:"include"}).then(r=>r.ok?r.json():{analyses:[]}).then(body=>{setAnalyses(body.analyses||[]);if(body.analyses?.[0]){const item=body.analyses[0] as Analysis;setAnalysisId(item.id);setTransactions(item.transactions);setFileName(item.fileName);setSummaryText(item.summary);}}).catch(()=>{});},[user]);
  const submitAuth = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!authMode) return; setAuthBusy(true); setAuthError(""); const form = new FormData(event.currentTarget); try { const endpoint=authMode==="forgot"?"forgot-password":authMode==="reset"?"reset-password":authMode; const response = await fetch(`${API_URL}/api/auth/${endpoint}`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.get("name"), email: form.get("email"), password: form.get("password"), token:resetToken }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Authentication failed."); if(authMode==="forgot"){if(body.resetToken){setResetToken(body.resetToken);setAuthMode("reset");}else{setAuthError("Check your email for the reset link.");}return;} if(authMode==="reset"){setAuthMode("login");setAuthError("Password updated. Log in with the new password.");return;} if(body.verificationToken){await fetch(`${API_URL}/api/auth/verify`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({token:body.verificationToken})});body.user.emailVerified=true;} setUser({ id: body.user.id, displayName: body.user.name, email: body.user.email,emailVerified:body.user.emailVerified }); setAuthMode(null); setTab("overview"); } catch (error) { setAuthError(error instanceof TypeError ? "The authentication server is offline. Stop old terminals and run npm run dev." : error instanceof Error ? error.message : "Authentication failed."); } finally { setAuthBusy(false); } };
  const logout = async () => { await fetch(`${API_URL}/api/auth/logout`, { method: "POST", credentials: "include" }).catch(()=>{}); setUser(null); setTransactions([]); setAnalyses([]); setAnalysisId(null); setTab("home"); };
  const expenses = useMemo(() => transactions.filter(t => t.amount < 0), [transactions]);
  const incomeTransactions = transactions.filter(t => t.amount > 0);
  const total = expenses.reduce((s,t) => s + Math.abs(t.amount), 0), income = incomeTransactions.reduce((s,t) => s + t.amount, 0);
  const byCategory = useMemo(() => Object.entries(expenses.reduce((a,t) => ({...a, [t.category]: (a[t.category] || 0) + Math.abs(t.amount)}), {} as Record<string,number>)).sort((a,b)=>b[1]-a[1]), [expenses]);
  const filtered = expenses.filter(t => t.description.toLowerCase().includes(query.toLowerCase()) || t.category.toLowerCase().includes(query.toLowerCase()));
  const top = byCategory[0];
  const summary = summaryText || (total ? `You spent ${money(total)} across ${expenses.length} purchases.` : "Upload a statement to see your spending story.");
  const ingest = async (file?: File) => { if (!file) return; setUploadBusy(true);setUploadError("");try{const form=new FormData();form.append("statement",file);const response=await fetch(`${API_URL}/api/analyze`,{method:"POST",credentials:"include",body:form});const body=await response.json();if(!response.ok)throw new Error(body.error||"Could not analyze this file.");const item=body.analysis as Analysis;setTransactions(item.transactions);setFileName(item.fileName);setSummaryText(item.summary);setAnalysisId(item.id);setAnalyses(list=>[item,...list]);setShowUpload(false);setTab("overview");}catch(error){setUploadError(error instanceof Error?error.message:"Upload failed.");}finally{setUploadBusy(false);} };
  const drop = (e: DragEvent) => { e.preventDefault(); setDragging(false); ingest(e.dataTransfer.files[0]); };
  const editCategory = async (id: string, category: Category) => {const previous=transactions;setTransactions(ts=>ts.map(t=>t.id===id?{...t,category,confidence:1,corrected:true}:t));if(!analysisId)return;const response=await fetch(`${API_URL}/api/analyses/${analysisId}/transactions/${id}`,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({category})});if(!response.ok)setTransactions(previous);};
  const openAnalysis=(item:Analysis)=>{setAnalysisId(item.id);setTransactions(item.transactions);setFileName(item.fileName);setSummaryText(item.summary);setTab("overview");};
  const known = expenses.filter(t => t.category !== "Other"), locals = known.filter(t=>t.local), brands = known.filter(t=>!t.local);
  const localScore = locals.length ? Math.round(locals.reduce((s,t)=>s+t.confidence,0)/locals.length*100) : 0, brandScore = brands.length ? Math.round(brands.reduce((s,t)=>s+t.confidence,0)/brands.length*100) : 0;

  return <main className={`theme-${theme}`}>
    <header className="topbar"><button className="brand" onClick={()=>setTab("home")}><span className="brandMark">S/S</span><span>Spend Sense</span></button>{isAuthenticated && <nav><button className={tab==="overview"?"active":""} onClick={()=>setTab("overview")}>Overview</button><button className={tab==="transactions"?"active":""} onClick={()=>setTab("transactions")}>Transactions</button><button className={tab==="fairness"?"active":""} onClick={()=>setTab("fairness")}>Fairness</button><button className={tab==="account"?"active":""} onClick={()=>setTab("account")}>Account</button></nav>}<div className="actions"><button className="demoNav" onClick={()=>{setDemoStep(0);setDemoPlaying(true);setShowDemo(true)}}>Demo</button><button className="themeToggle" aria-label={`Switch to ${theme === "light" ? "dark" : "light"} mode`} onClick={toggleTheme}>{theme === "light" ? "Dark" : "Light"}</button>{isAuthenticated && <button className="uploadButton" onClick={()=>setShowUpload(true)}>Upload ↗</button>}</div></header>
    <section className="shell">
      {tab === "home" && <section className="homePage"><div className="homeHero"><span className="eyebrow">YOUR MONEY, MADE LEGIBLE</span><h1>Know where<br/>it went.</h1><p>Upload a bank statement. Get clean categories, a useful monthly summary and a clear view of every transaction.</p>{!isAuthenticated ? <div className="authActions"><button className="loginButton" onClick={()=>{setAuthError("");setAuthMode("login")}}>Log in</button><button className="signupButton" onClick={()=>{setAuthError("");setAuthMode("signup")}}>Sign up</button></div> : <div className="signedInActions"><span>Signed in as {user?.displayName}</span><button onClick={()=>setTab("overview")}>Open overview</button><button onClick={logout}>Sign out</button></div>}</div><div className="homeProof"><article><span>01</span><h2>Sort the mess</h2><p>Turn raw bank descriptions into categories you can review and correct.</p></article><article><span>02</span><h2>See the month</h2><p>Understand what came in, what went out and which categories mattered.</p></article><article><span>03</span><h2>Check the model</h2><p>See whether local merchants are treated as consistently as known brands.</p></article></div></section>}

      {tab !== "home" && <div className="sectionHead"><div><span className="eyebrow">{tab.toUpperCase()}</span><h1>{tab === "overview" ? "Overview" : tab === "transactions" ? "Transactions" : tab === "fairness" ? "Fairness" : "Account"}</h1></div><div className="statementPill">{tab==="account"?user?.email:fileName}</div></div>}

      {tab === "overview" && analyses.length > 0 && <div className="historyBar"><span>Saved analyses</span><div>{analyses.slice(0,6).map(item=><button key={item.id} className={item.id===analysisId?"active":""} onClick={()=>openAnalysis(item)}>{item.fileName}<small>{new Date(item.createdAt).toLocaleDateString()}</small></button>)}</div></div>}

      {tab === "overview" && transactions.length === 0 && <EmptyAnalysis onUpload={()=>setShowUpload(true)}/>} 
      {tab === "overview" && transactions.length > 0 && <>
        <div className="stats"><article><span>Total spent</span><strong>{money(total)}</strong><small>{expenses.length} outgoing {expenses.length === 1 ? "payment" : "payments"}</small></article><article><span>Money in</span><strong>{money(income)}</strong><small>{incomeTransactions.length} incoming {incomeTransactions.length === 1 ? "payment" : "payments"}</small></article><article><span>Transactions</span><strong>{transactions.length}</strong><small>{byCategory.length} spending categories</small></article><article><span>Avg. confidence</span><strong>{expenses.length ? Math.round(expenses.reduce((s,t)=>s+t.confidence,0)/expenses.length*100) : 0}%</strong><small>Not accuracy</small></article></div>
        <div className="grid"><article className="panel breakdown"><div className="panelHead"><div><span className="kicker">BREAKDOWN</span><h2>By category</h2></div><button onClick={()=>setTab("transactions")}>View all</button></div><div className="bars">{byCategory.slice(0,6).map(([cat,val])=><div className="barRow" key={cat}><div className="barLabel"><b>{cat}</b><span>{money(val)}</span></div><div className="track"><i style={{width:`${Math.max(3,val/(top?.[1]||1)*100)}%`}}/></div><em>{Math.round(val/total*100)}%</em></div>)}</div></article>
          <article className="panel insight"><span className="kicker">SUMMARY</span><h2>This month</h2><p>{summary}</p><div className="insightFoot"><span>{expenses.length} transactions</span><button onClick={()=>setTab("transactions")}>Details</button></div></article></div>
        <article className="panel recent"><div className="panelHead"><div><span className="kicker">RECENT</span><h2>Transactions</h2></div><button onClick={()=>setTab("transactions")}>View {expenses.length}</button></div><TransactionRows rows={expenses.slice(0,5)} onEdit={editCategory}/></article>
      </>}

      {tab === "transactions" && transactions.length === 0 && <EmptyAnalysis onUpload={()=>setShowUpload(true)}/>} 
      {tab === "transactions" && transactions.length > 0 && <article className="panel transactionPanel"><div className="tableTools"><div className="search"><span>⌕</span><input aria-label="Search transactions" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search merchant or category"/></div><span>{filtered.length} transactions</span></div><TransactionRows rows={filtered} onEdit={editCategory}/></article>}

      {tab === "fairness" && transactions.length === 0 && <EmptyAnalysis onUpload={()=>setShowUpload(true)}/>} 
      {tab === "fairness" && transactions.length > 0 && <div className="fairGrid"><article className="panel fairnessHero"><span className="kicker">MODEL CHECK</span><h2>Local vs known merchants</h2><p>Average prediction confidence for two merchant groups. A smaller gap means more consistent treatment.</p><div className="scoreCompare"><Score label="Known brands" value={brandScore}/><div className="versus">vs</div><Score label="Local merchants" value={localScore}/></div><div className="gap">{Math.abs(brandScore-localScore)} point confidence gap · {brandScore-localScore > 10 ? "Review needed" : "Within target"}</div></article><article className="panel methodology"><span className="kicker">METHOD</span><h2>How it works</h2><ol><li><b>01</b><span>Split merchant names into known brands and local businesses.</span></li><li><b>02</b><span>Compare average confidence and review errors.</span></li><li><b>03</b><span>Use corrections in the next training cycle.</span></li></ol><p className="note">Confidence is not accuracy. A labeled test set is required for a proper audit.</p></article></div>}
      {tab === "account" && user && <AccountPanel user={user} apiUrl={API_URL} onLogout={logout}/>} 
    </section>

    {authMode && <div className="modal" role="dialog" aria-modal="true" aria-label="Account access" onMouseDown={e=>{if(e.target===e.currentTarget)setAuthMode(null)}}><form className="authCard" onSubmit={submitAuth}><button className="close" type="button" aria-label="Close" onClick={()=>setAuthMode(null)}>×</button><span className="kicker">ACCOUNT</span><h2>{authMode==="login"?"Log in":authMode==="signup"?"Sign up":authMode==="forgot"?"Reset password":"Choose a new password"}</h2>{authMode === "signup" && <label>Name<input name="name" autoComplete="name" minLength={2} required/></label>}{authMode!=="reset"&&<label>Email<input name="email" type="email" autoComplete="email" required/></label>}{authMode!=="forgot"&&<label>Password<input name="password" type="password" autoComplete={authMode === "login" ? "current-password" : "new-password"} minLength={8} required/></label>}{authError && <p className="authError" role="alert">{authError}</p>}<button className="authSubmit" disabled={authBusy}>{authBusy?"Please wait…":authMode==="login"?"Log in":authMode==="signup"?"Create account":authMode==="forgot"?"Continue":"Update password"}</button>{authMode==="login"&&<button className="authSwitch" type="button" onClick={()=>{setAuthError("");setAuthMode("forgot")}}>Forgot password?</button>}<button className="authSwitch" type="button" onClick={()=>{setAuthError("");setAuthMode(authMode === "login" ? "signup" : "login")}}>{authMode === "login" ? "Need an account? Sign up" : "Back to login"}</button></form></div>}
    {showDemo && <div className="modal demoModal" role="dialog" aria-modal="true" aria-label="Spend Sense demo" onMouseDown={e=>{if(e.target===e.currentTarget)setShowDemo(false)}}><div className="demoPlayer"><button className="close demoClose" aria-label="Close demo" onClick={()=>setShowDemo(false)}>×</button><div className="demoScreen"><DemoVisual type={demoScenes[demoStep].visual}/><div className="demoCaption"><span>{demoScenes[demoStep].number} / 05</span><h2>{demoScenes[demoStep].title}</h2><p>{demoScenes[demoStep].body}</p></div></div><div className="demoControls"><button aria-label={demoPlaying ? "Pause demo" : "Play demo"} onClick={()=>setDemoPlaying(value=>!value)}>{demoPlaying ? "Pause" : "Play"}</button><div className="demoTimeline">{demoScenes.map((scene,index)=><button key={scene.number} className={index===demoStep?"current":""} aria-label={`Show step ${index+1}: ${scene.title}`} onClick={()=>{setDemoStep(index);setDemoPlaying(false)}}><i/></button>)}</div><button onClick={()=>setDemoStep(step=>(step+1)%demoScenes.length)}>Next</button></div></div></div>}
    {showUpload && <div className="modal" role="dialog" aria-modal="true" aria-label="Upload statement" onMouseDown={e=>{if(e.target===e.currentTarget&&!uploadBusy)setShowUpload(false)}}><div className="uploadCard"><button className="close" disabled={uploadBusy} onClick={()=>setShowUpload(false)}>×</button><span className="kicker">IMPORT · CSV / XLSX / PDF</span><h2>{uploadBusy?"Analyzing…":"Upload your statement"}</h2><p>Your file is sent securely to the categorization service and the resulting analysis is saved to your account.</p><div className={`dropzone ${dragging?"dragging":""}`} onDragOver={e=>{e.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={drop} onClick={()=>!uploadBusy&&input.current?.click()}><span className="uploadIcon">↑</span><b>{uploadBusy?"Cleaning and categorizing transactions":"Drop CSV, XLSX or PDF here"}</b><span>{uploadBusy?"Please keep this window open":"or click to choose a file"}</span><input ref={input} type="file" accept=".csv,.xlsx,.pdf,text/csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,application/pdf" hidden onChange={(e:ChangeEvent<HTMLInputElement>)=>ingest(e.target.files?.[0])}/></div>{uploadError&&<p className="authError">{uploadError}</p>}<small>Spreadsheet columns: date, description and amount—or separate debit and credit columns. PDFs must contain selectable text.</small></div></div>}
  </main>;
}

function Score({label,value}:{label:string,value:number}) { return <div className="score"><strong>{value}%</strong><span>{label}</span><div><i style={{width:`${value}%`}}/></div></div> }
function EmptyAnalysis({onUpload}:{onUpload:()=>void}) { return <section className="emptyAnalysis"><span className="kicker">NO ANALYSIS YET</span><h2>Upload a CSV file<br/>to get your analysis.</h2><p>Your overview, transactions and fairness check will appear here after the file is processed.</p><button onClick={onUpload}>Upload CSV ↗</button></section> }
function AccountPanel({user,apiUrl,onLogout}:{user:NonNullable<SignedInUser>;apiUrl:string;onLogout:()=>void}) { const [message,setMessage]=useState(""); const remove=async()=>{if(!window.confirm("Delete your account and every saved analysis? This cannot be undone."))return;const response=await fetch(`${apiUrl}/api/account`,{method:"DELETE",credentials:"include"});if(response.ok)onLogout();else setMessage("Account deletion failed.");}; return <section className="accountPanel"><div><span className="kicker">PROFILE</span><h2>{user.displayName}</h2><p>{user.email}</p><p>{user.emailVerified?"Email verified":"Email verification pending"}</p></div><div><span className="kicker">YOUR DATA</span><h2>Account controls</h2><p>Your statements, transactions and corrections are private to this account.</p>{message&&<p>{message}</p>}<button onClick={onLogout}>Sign out</button><button className="danger" onClick={remove}>Delete account and data</button></div></section> }
function DemoVisual({type}:{type:string}) { if(type==="upload") return <div className="demoGraphic demoUpload"><span>CSV · XLSX · PDF</span><b>statement_july.xlsx</b><i>Upload complete</i></div>; if(type==="overview") return <div className="demoGraphic demoOverview"><div><span>Total spent</span><b>₹36,136</b></div><div><span>Transactions</span><b>11</b></div><section><i style={{width:"82%"}}/><i style={{width:"48%"}}/><i style={{width:"31%"}}/></section></div>; if(type==="transactions") return <div className="demoGraphic demoRows"><div><b>Rina&apos;s Kitchen</b><span>Food & Dining</span></div><div><b>Uber India</b><span>Transport</span></div><div><b>Netflix</b><span>Entertainment</span></div></div>; if(type==="fairness") return <div className="demoGraphic demoScores"><div><b>96%</b><span>Known brands</span></div><em>vs</em><div><b>82%</b><span>Local merchants</span></div></div>; return <div className="demoGraphic demoResult"><b>₹36,136</b><span>understood in under a minute.</span></div> }
function TransactionRows({rows,onEdit}:{rows:Transaction[];onEdit:(id:string,c:Category)=>void}) { const categories = Object.keys(palette) as Category[]; return <div className="rows">{rows.map(t=><div className="transaction" key={t.id}><div className="merchantIcon" style={{borderColor:palette[t.category],color:palette[t.category]}}>{t.description.charAt(0)}</div><div className="merchant"><b>{t.description.replace(/\b\w/g,c=>c.toUpperCase()).slice(0,35)}</b><span>{new Date(t.date+"T00:00:00").toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})}{t.corrected?" · corrected":""}</span></div><select aria-label={`Category for ${t.description}`} value={t.category} onChange={e=>onEdit(t.id,e.target.value as Category)} style={{borderColor:palette[t.category],color:palette[t.category]}}>{categories.map(c=><option key={c}>{c}</option>)}</select><div className="confidence"><span>{Math.round(t.confidence*100)}%</span></div><strong className="amount">{money(t.amount)}</strong></div>)}{!rows.length&&<div className="empty">No matching transactions.</div>}</div> }
